### ISSUE TITLE
TypeError: can't convert complex to float

### ISSUE THREAD

**Issue by KodeWorker** [coin-or/pulp#266]
Hi guys,
When I using PuLP in my [project](https://github.com/KodeWorker/pyEasyTL), I came across an error message:

<pre><code>
Traceback (most recent call last):
  File "demo_office_caltech.py", line 37, in <module>
    Acc2, _ = EasyTL(Xs,Ys,Xt,Yt)
  File "D:\GitHub_repos\pyEasyTL\EasyTL.py", line 115, in EasyTL
    Mcj = label_prop(C,m,Dct,lp)
  File "D:\GitHub_repos\pyEasyTL\label_prop_v2.py", line 33, in label_prop
    model.solve()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\pyEasyTL\lib\site-packages\pulp\pulp.py", line 1713, in solve
    status = solver.actualSolve(self, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\pyEasyTL\lib\site-packages\pulp\solvers.py", line 1408, in actualSolve
    return self.solve_CBC(lp, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\pyEasyTL\lib\site-packages\pulp\solvers.py", line 1431, in solve_CBC
    vs, variablesNames, constraintsNames, objectiveName = lp.writeMPS(tmpMps, rename = 1)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\pyEasyTL\lib\site-packages\pulp\pulp.py", line 1450, in writeMPS
    constraintsNames, variablesNames, cobj.name = self.normalisedNames()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\pyEasyTL\lib\site-packages\pulp\pulp.py", line 1220, in normalisedNames
    for k in self.variables():
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\pyEasyTL\lib\site-packages\pulp\pulp.py", line 1297, in variables
    if self.objective:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\envs\pyEasyTL\lib\site-packages\pulp\pulp.py", line 599, in __bool__
    return (float(self.constant) != 0.0) or (len(self) > 0)
TypeError: can't convert complex to float
</code></pre>

I found out that self.constant in line 599 of pulp.py became **0j** while running my demo code.
I found myself a workaround by changing the following code:
1. float(self.constant) -> float(abs(self.constant)) in line 599 of pulp.py
2. cobj[v] -> abs(cobj[v]) in line 1492 of pulp.py

And the code ran smoothly an the results are expected.

What cause this error?
Is this a valid workaround?

**Comment by pchtsp** [comment]
Hello!

Do you have a series of steps to reproduce the error with your project ?

I suspect it has something to do with the Dct parameter.

F.

**Comment by stumitchell** [comment]
@KodeWorker I think you should move the abs() call to your code. i.e not change the code in pulp.

Pulp as a library doesn't deal with complex numbers. So I think you should make sure you don't pass complex numbers into pulp.

**Comment by KodeWorker** [comment]
Thanks for the help
@pchtsp Your suspicion is correct! It is the Dct parameter in my code that cause this problem
@stumitchell  Putting abs() in my code actually makes more sense, due to that Dct parameter (distance measurement) should not be complex.
