### ISSUE TITLE
Failing testsuite

### ISSUE THREAD

**Issue by SnarkBoojum** [coin-or/pulp#300]
I unpacked version 2.1's sources, then: python3 setup.py test.

It did run quite a few tests, then:
```
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    setup(name="PuLP",
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 238, in run
    self.run_tests()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 256, in run_tests
    test = unittest.main(
  File "/usr/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.8/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.8/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.8/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.8/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.8/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib/python3.8/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.8/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.8/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 41, in loadTestsFromModule
    tests.append(TestLoader.loadTestsFromModule(self, module))
  File "/usr/lib/python3.8/unittest/loader.py", line 124, in loadTestsFromModule
    tests.append(self.loadTestsFromTestCase(obj))
  File "/usr/lib/python3.8/unittest/loader.py", line 93, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
  File "/usr/lib/python3.8/unittest/suite.py", line 24, in __init__
    self.addTests(tests)
  File "/usr/lib/python3.8/unittest/suite.py", line 57, in addTests
    for test in tests:
TypeError: __init__() missing 1 required positional argument: 'solver'
```

**Comment by pchtsp** [comment]
Good day! thanks for reporting. Could you please give more details on what you are using. how did you install pulp, which version of python (3.8 it appears?). Did you try the github version? I guess it's Linux? which one?

**Comment by SnarkBoojum** [comment]
I took the github tarball for 2.1 ; Python version is 3.8.3 and setuptools 46.1.3. It's a Debian unstable.

What is strange is that it does test quite a few things before it stops with the given error. Is there a way to run the tests separately to pinpoint which one gives issues?

**Comment by pchtsp** [comment]
Have you tried the pypi version (pip install pulp)?

F.

**Comment by pchtsp** [comment]
Also, where did you got 'python3 setup.py test'?

To test you should run 

pulptest

In the command line.

**Comment by SnarkBoojum** [comment]
Well, there's a setup.py, so I'm using the usual command to run the tests in that case...

**Comment by SnarkBoojum** [comment]
pulptest says:
```
Ran 127 tests in 21.837s

OK
```

**Comment by pchtsp** [comment]
Can you try the branch here:

https://github.com/coin-or/pulp/tree/fix_300

It should allow testing from setup.py.

F.
