### ISSUE TITLE
 status = solver.actualSolve(self, **kwargs) AttributeError: 'NoneType' object has no attribute 'actualSolve'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coin-or/pulp#62]
```
Hi,

I installed PuLP1.5.6 on macosx lion 10.8.5 and when I tried to execute this 
command line:

python test1.py

I received:

Traceback (most recent call last):
  File "test1.py", line 33, in <module>
    prob.solve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PuLP-1.5.6-py2.7.egg/pulp/pulp.py", line 1619, in solve
    status = solver.actualSolve(self, **kwargs)
AttributeError: 'NoneType' object has no attribute 'actualSolve'

test1.py is in PuLP-1.5.6/examples

When I did in the python 2.7.5 interpreter this command line 
"pulp.pulpTestAll()" I received:

Solver pulp.solvers.PULP_CBC_CMD unavailable
Solver pulp.solvers.CPLEX_DLL unavailable
Solver pulp.solvers.CPLEX_CMD unavailable
Solver pulp.solvers.CPLEX_PY unavailable
Solver pulp.solvers.COIN_CMD unavailable
Solver pulp.solvers.COINMP_DLL unavailable
Solver pulp.solvers.GLPK_CMD unavailable
Solver pulp.solvers.XPRESS unavailable
Solver pulp.solvers.GUROBI unavailable
Solver pulp.solvers.GUROBI_CMD unavailable
Solver pulp.solvers.PYGLPK unavailable
Solver pulp.solvers.YAPOSIB unavailable

When I did "sudo pulptest" I received:

Testing zero subtraction
     Testing continuous LP solution
     Testing maximize continuous LP solution
     Testing unbounded continuous LP solution
     Testing Long Names
     Testing repeated Names
     Testing zero constraint
     Testing zero objective
     Testing LpVariable (not LpAffineExpression) objective
     Testing MIP solution
     Testing MIP relaxation
     Testing feasibility problem (no objective)
     Testing an infeasible problem
     Testing an integer infeasible problem
     Testing column based modelling
     Testing dual variables and slacks reporting
     Testing fractional constraints
     Testing elastic constraints (no change)
     Testing elastic constraints (freebound)
     Testing elastic constraints (penalty unchanged)
     Testing elastic constraints (penalty unbounded)
* Solver pulp.solvers.PULP_CBC_CMD passed.
Solver pulp.solvers.CPLEX_DLL unavailable
Solver pulp.solvers.CPLEX_CMD unavailable
Solver pulp.solvers.CPLEX_PY unavailable
Solver pulp.solvers.COIN_CMD unavailable
Solver pulp.solvers.COINMP_DLL unavailable
Solver pulp.solvers.GLPK_CMD unavailable
Solver pulp.solvers.XPRESS unavailable
Solver pulp.solvers.GUROBI unavailable
Solver pulp.solvers.GUROBI_CMD unavailable
Solver pulp.solvers.PYGLPK unavailable
Solver pulp.solvers.YAPOSIB unavailable

What ca I do?



```

Original issue reported on code.google.com by `poleposi...@gmail.com` on 27 Apr 2014 at 3:43

**Comment by Aikia0710** [comment]
> http://wolfpaulus.com/jounal/mac/installing_python_osx/

hi, i have faced the same problem right now, do you know how to solve the problem?
AttributeError: 'NoneType' object has no attribute 'actualSolve'

**Comment by pchtsp** [comment]
Please create another issue, together with the python code you are using, the python version, the pulp version, etc.
This error happens because you do not have access to the solver you are trying to use.

**Comment by roomrys** [comment]
Hello, just adding some docs to an old issue (that likely has many different situations that lead to this problem), but 

## Error
I've run into this error:
```python
Traceback (most recent call last):
  File "/Users/me/Projects/pulp/liezl_test_and_debug.py", line 85, in <module>
    status = prob.solve(solver)
  File "/Users/me/Projects/pulp/pulp/pulp.py", line 2007, in solve
    status = solver.actualSolve(self, **kwargs)
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'actualSolve'
```

### Recreate MVP
when running the following example code from the README:
```python
from pulp import *


# Example code
x = LpVariable("x", 0, 3)
y = LpVariable("y", 0, 1)
prob: LpProblem = LpProblem("myProblem", LpMinimize)
prob += x + y <= 2
prob += -4 * x + y

# Error
status = prob.solve(solver)
```

### System
with this set-up:
```bash
(pulp) liezlmaree:~$python --version
Python 3.13.2
(pulp) liezlmaree:~$uname -a
Darwin Liezls-MBP.attlocal.net 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64
(pulp) liezlmaree:~$pip list
Package Version
------- -------
pip     25.0.1
PuLP    3.0.2
```
.

## Investigation
It was a bit weird that `LpProblem.solver is None` when we try to `LpProblem.solve`. So, obviously, I try to pass in a solver when we call `LpProblem.solve`, 

### Error 2
but then I run into this new error:
```python
Traceback (most recent call last):
  File "/Users/me/Projects/pulp/liezl_test_and_debug.py", line 81, in <module>
    status = prob.solve(pulp.PULP_CBC_CMD(path=pulp_cbc_path.replace("arm64", "64")))
  File "/Users/me/Projects/pulp/pulp/pulp.py", line 2007, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/Users/me/Projects/pulp/pulp/apis/coin_api.py", line 354, in actualSolve
    raise PulpSolverError(
    ...<2 lines>...
    )
pulp.apis.core.PulpSolverError: PULP_CBC_CMD: Not Available (check permissions on /Users/me/Projects/pulp/pulp/solverdir/cbc/osx/arm64/cbc)
```

### Recreate Error 2 MVP
when I run this code:
```python
from pulp import *


# Example code
x = LpVariable("x", 0, 3)
y = LpVariable("y", 0, 1)
prob: LpProblem = LpProblem("myProblem", LpMinimize)
prob += x + y <= 2
prob += -4 * x + y

# This will fail: everything was already messed up on import with the incorrect path.
status = prob.solve(pulp.PULP_CBC_CMD())

# Error
status = prob.solve(solver)
```
.

### Reason (but not solution)
Upon further investigation, it seems that the `pulp_cbc_path` was being set incorrectly to include `arm64` in the path instead of `64` where the cbc executable actually resides:
https://github.com/coin-or/pulp/blob/ebbbfdedce62a3c1815d98bbb4caada513782941/pulp/apis/core.py#L122
do to this bit of code changing `arch="arm64"`:
https://github.com/coin-or/pulp/blob/ebbbfdedce62a3c1815d98bbb4caada513782941/pulp/apis/core.py#L151-L157
. Ooorrrrrr maybe cbc should be installed to a path with `arm64` included instead of `64`?
<img width="194" alt="Image" src="https://github.com/user-attachments/assets/00543aed-29aa-4973-95ff-a77fb91c39fe" />

## Workaround
Anywho, this is the workaround I have so far to let me (and other that run into this) at least try out the library:
```python
from pulp import *
from pulp.apis import COIN_CMD

RUN_INTO_PROBLEM = False
TRY_PULP_CBC = True

solver = None  # The default solver is used if None is passed.
if not RUN_INTO_PROBLEM:
    # This is a copy of the __init__ method from pulp.PULP_CBC_CMD
    def copied__init__(
        self,
        mip=True,
        msg=True,
        timeLimit=None,
        gapRel=None,
        gapAbs=None,
        presolve=None,
        cuts=None,
        strong=None,
        options=None,
        warmStart=False,
        keepFiles=False,
        path=None,
        threads=None,
        logPath=None,
        timeMode="elapsed",
        maxNodes=None,
    ):
        if path is not None:
            raise PulpSolverError("Use COIN_CMD if you want to set a path")
        # check that the file is executable
        COIN_CMD.__init__(
            self,
            path=self.pulp_cbc_path,
            mip=mip,
            msg=msg,
            timeLimit=timeLimit,
            gapRel=gapRel,
            gapAbs=gapAbs,
            presolve=presolve,
            cuts=cuts,
            strong=strong,
            options=options,
            warmStart=warmStart,
            keepFiles=keepFiles,
            threads=threads,
            logPath=logPath,
            timeMode=timeMode,
            maxNodes=maxNodes,
        )

    # Reverse the damage done when everything was imported and pulp_cbc_path was incorrect.
    pulp_cbc_path = pulp_cbc_path.replace("arm64", "64")  # Fix the path

    # This is a copy of the pre-init PULP_CBC_CMD logic.
    if os.name != "nt":
        if not os.access(pulp_cbc_path, os.X_OK):
            import stat

            os.chmod(pulp_cbc_path, stat.S_IXUSR + stat.S_IXOTH)

    pulp.PULP_CBC_CMD.pulp_cbc_path = pulp_cbc_path
    pulp.PULP_CBC_CMD.__init__ = copied__init__
    pulp.PULP_CBC_CMD.available = COIN_CMD.available
    pulp.PULP_CBC_CMD.actualSolve = COIN_CMD.actualSolve

    # Create the solver (pulp installs with a pre-compiled cbc executable)
    solver = pulp.PULP_CBC_CMD(
        msg=True,
    )

# Example code
x = LpVariable("x", 0, 3)
y = LpVariable("y", 0, 1)
prob: LpProblem = LpProblem("myProblem", LpMinimize)
prob += x + y <= 2
prob += -4 * x + y

# This will fail: everything was already messed up on import with the incorrect path.
if TRY_PULP_CBC and RUN_INTO_PROBLEM:
    status = prob.solve(pulp.PULP_CBC_CMD())

status = prob.solve(solver)
```
.

# Related
- #765
- #766
