### ISSUE TITLE
highs solver fails test in Ubuntu when showing log messages

### ISSUE THREAD

**Issue by pchtsp** [coin-or/pulp#684]
Maybe @siwy knows about this since it was him who brought the changes with setLogCallback in https://github.com/coin-or/pulp/commit/6a8e4631fdc09575834b2017e339c74017a5ac07. 
The test that fails is `test_msg_arg`. It only fails in Ubuntu, not in mac:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/pulp/tests/test_pulp.py", line 842, in test_msg_arg
    pulpTestCheck(
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/pulp/tests/test_pulp.py", line 1556, in pulpTestCheck
    status = prob.solve(solver, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/pulp/pulp.py", line 1920, in solve
    status = solver.actualSolve(self, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/pulp/apis/highs_api.py", line 394, in actualSolve
    self.createAndConfigureSolver(lp)
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/pulp/apis/highs_api.py", line 301, in createAndConfigureSolver
    lp.solverModel.setLogCallback(*callbackTuple)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Highs' object has no attribute 'setLogCallback'

**Comment by tomaszG247** [comment]
I am experiencing the same error message trying to solve a model with HiGHS solver interface

```Exception has occurred: AttributeError
'Highs' object has no attribute 'setLogCallback'
  File "C:\Users\TGi\OneDrive - CSEM S.A\Documents\Code\pentagon\pentagon\pentagon_models.py", line 1730, in solveProblem
    prob.solve(solver=solver)
```

I am on Windows, 
I got highspy == 1.5.3 and pulp = 2.8.0 from Pypi.

I am calling my solver simply as `solver = pu.apis.HiGHS(
		msg=True,
	) `

**Comment by pchtsp** [comment]
I added a comment in highspy repo. Feel free to leave a comment there or create a new issue there: https://github.com/ERGO-Code/HiGHS/issues/1633

**Comment by jajhall** [comment]
The current [pypi](https://pypi.org/project/highspy/) version of HiGHS is still the rogue v1.5.3 in which setLogCallback was deleted from highspy.

However, [v1.7.1.dev1](https://pypi.org/project/highspy/#history) is now available. This allows the new [general callback mechanism](https://ergo-code.github.io/HiGHS/stable/callbacks/) to be used.

It would be good if this beta release could be tested



    or would you know a way to provide logs without using this functionality?

See https://ergo-code.github.io/HiGHS/dev/interfaces/python/#Logging

**Comment by HAHHHD** [comment]
@jajhall   I've intalled the lastest v1.7.1.dev1, but when I want to warmstart an LP with an initial basis it shows "AttributeError: 'Highs' object has no attribute 'setBasis'". Is setBasis() still not included in this highspy version?

**Comment by pchtsp** [comment]
this is fixed
